[    
 {
  "Sr No": 1,
  "Team": "Bombaywala 11",
  "PlayerName": "Darshit Yogesh Vohra",
  "Address": "Surendragarh Seminary hills near Gupta chowk, Nagpur",
  "DOB": "03-03-2008",
  "Contact": "8484919018",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=137BH-azoeXhfuw2yYBHsvVRZnaxwWHeV"
 },
 {
  "Sr No": 2,
  "Team": "Bombaywala 11",
  "PlayerName": "Hritik Omprakash Vyas",
  "Address": "Civil lines",
  "DOB": "21-10-1998",
  "Contact": "8975705008",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1F1oyVuH02erzLhvX-lR-BodUiyriXP0K"
 },
 {
  "Sr No": 3,
  "Team": "Bombaywala 11",
  "PlayerName": "Pratik Omprakash Vyas",
  "Address": "Civil lines",
  "DOB": "20-03-2001",
  "Contact": "7843085584",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1_b9_nAFvAMDR8k-BMgFzK-DFdjfcj9Si"
 },
 {
  "Sr No": 4,
  "Team": "Bombaywala 11",
  "PlayerName": "Rishabh Pradeep Vyas",
  "Address": "Nagpur",
  "DOB": "10-09-2002",
  "Contact": "8975577008",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1FDfkT0WSfS5SGsjjjisCeIl7S19A6l9l"
 },
 {
  "Sr No": 5,
  "Team": "Bombaywala 11",
  "PlayerName": "Rushab Thakur",
  "Address": "F402 White Pelican Nava Naroda Road, Hanspura, Ahmedabad - 382330",
  "DOB": "07-02-1999",
  "Contact": "9924717402",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1q3JZS0COJcqg7Duwn7SporWxtU53DN6x"
 },
 {
  "Sr No": 6,
  "Team": "CSK",
  "PlayerName": "Nayan Mahesh Trivedi",
  "Address": "Seminary hills, Manav Seva Nagar, Nagpur",
  "DOB": "13-10-1999",
  "Contact": "7028133306",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1sOr119qhNPIXCE-Gj8lhWK1A4iYt7LGS"
 },
 {
  "Sr No": 7,
  "Team": "CSK",
  "PlayerName": "Mahesh Pannalalji Trivedi",
  "Address": "Seminary hills, Manav Seva Nagar, Nagpur",
  "DOB": "25-09-1973",
  "Contact": "7391999711",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1_vHRVZjyzuU8xobpMeN40OvXW50qlxpR"
 },
 {
  "Sr No": 8,
  "Team": "CSK",
  "PlayerName": "Navneet Mahesh Trivedi",
  "Address": "Seminary hills, Manav Seva Nagar, Nagpur",
  "DOB": "06-03-2002",
  "Contact": "9561794502",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=16ViHfaXmZK4wIYDJpObKEkdiTz6A_j87"
 },
 {
  "Sr No": 9,
  "Team": "CSK",
  "PlayerName": "Dipesh Ravindra Dave",
  "Address": "Near Shanti Bhavan, Golchha Marg, Karachi Line, Sadar, Nagpur",
  "DOB": "20-06-1995",
  "Contact": "8975975715",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1PbusEP8Hl5sVYEUbi0Hc4JsoIi-c67BX"
 },
 {
  "Sr No": 10,
  "Team": "CSK",
  "PlayerName": "Ayush Murli Joshi",
  "Address": "Surendra ghad, Seminary hills, Nagpur",
  "DOB": "03-10-2004",
  "Contact": "9075857808",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1gN6imgFbpEEBk8M7aafJiG-dNXhITma5"
 },
 {
  "Sr No": 11,
  "Team": "Director King - Srimali Warriors",
  "PlayerName": "Mayur Ajay Vyas",
  "Address": "Ajay Vyas",
  "DOB": "12-11-1990",
  "Contact": "6301642515",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1oN17uJqy4sqUb0Z9un5G1ZRTKw2NL5Y1"
 },
 {
  "Sr No": 12,
  "Team": "Director King - Srimali Warriors",
  "PlayerName": "Pratiek Satish Vyas",
  "Address": "Satish Vyas",
  "DOB": "10-05-2006",
  "Contact": "7206470370",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1XiQ149CI7X5xDfNOto11xkGrFsaFcC0e"
 },
 {
  "Sr No": 13,
  "Team": "Director King - Srimali Warriors",
  "PlayerName": "Atharva Joshi",
  "Address": "Zenda chowk, Dharampeth, Nagpur",
  "DOB": "28-02-2025",
  "Contact": "8421473397",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=19m2wajWcEzhZ8AGQdrqHsXj2D_-YHI0d"
 },
 {
  "Sr No": 14,
  "Team": "Director King - Srimali Warriors",
  "PlayerName": "Akshad Manoj Joshi",
  "Address": "604 Bhagwaghar Complex, opp Naturals Ice Cream, Dharampeth",
  "DOB": "19-03-2005",
  "Contact": "8788060029",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=12ToJO817mR7o8v2vzsS8pr84TiFRnI_R"
 },
 {
  "Sr No": 15,
  "Team": "Director King - Srimali Warriors",
  "PlayerName": "Roshan Manishi Joshi",
  "Address": "Bhagwaghar Complex, opp Natural Ice-cream, Dharampeth",
  "DOB": "24-12-1997",
  "Contact": "7020080425",
  "Speciality": "Keeping",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=126g6hfG05E890NuuAODY4xmmyMXUrl2H"
 },
 {
  "Sr No": 16,
  "Team": "Director King - Srimali Warriors",
  "PlayerName": "Pratik Ajay Vyas",
  "Address": "New Itwari Road, Nagpur",
  "DOB": "01-12-5",
  "Contact": "9860039432",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1ZtNldfs3Qlfhrw79rBhuXtzw1hPN8Q5U"
 },
 {
  "Sr No": 17,
  "Team": "KKR",
  "PlayerName": "Dilip Liladhar Trivedi",
  "Address": "Gandhi Putla CA Road, Nagpur",
  "DOB": "19-01-1983",
  "Contact": "9923992000",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1Jf7A0wHWMV1avgVBbnerFs2GGjkxk9tk"
 },
 {
  "Sr No": 18,
  "Team": "KKR",
  "PlayerName": "Toshi Girish Trivedi",
  "Address": "Badkas chowk, Mahal, Nagpur",
  "DOB": "24-08-1993",
  "Contact": "9096806858",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": ""
 },
 {
  "Sr No": 19,
  "Team": "KKR",
  "PlayerName": "Saurav Nitin Trivedi",
  "Address": "Nagpur",
  "DOB": "16-12-1999",
  "Contact": "8766728876",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1X2eQKsPo_HVc5WvrsmQBdBmA6ziAdepJ"
 },
 {
  "Sr No": 20,
  "Team": "KKR",
  "PlayerName": "Nitin Shantilal Trivedi",
  "Address": "Nagpur",
  "DOB": "05-11-1974",
  "Contact": "9823103080",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1a5YRG5XEGjo71cYyqgROYrg_G0xth799"
 },
 {
  "Sr No": 21,
  "Team": "KKR",
  "PlayerName": "Gaurav Dave",
  "Address": "Badkas Square, Chitaroli",
  "DOB": "28-03-2003",
  "Contact": "9307667179",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1rgUsFHyL2154EK4Ldp0K-u2TLQpA2ZVa"
 },
 {
  "Sr No": 22,
  "Team": "Nagpur Titans",
  "PlayerName": "Ujjwal Oza",
  "Address": "Seminary Hills, Nagpur",
  "DOB": "12-07-2004",
  "Contact": "9579224450",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1pY05_X7th4Hepx42A_URyiighu6H3_XP"
 },
 {
  "Sr No": 23,
  "Team": "Nagpur Titans",
  "PlayerName": "Yogesh Harish Ojha",
  "Address": "Opp plot no 85, Gajanan Prasaad Society, Seminary Hills, Nagpur 440006",
  "DOB": "02-11-2000",
  "Contact": "7843061681",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1NrzTqgsptYJh5XaEy7X_gUZS4YNPws72"
 },
 {
  "Sr No": 24,
  "Team": "Nagpur Titans",
  "PlayerName": "Shubham Ramchandra Ozha",
  "Address": "Surendragad",
  "DOB": "15-09-1995",
  "Contact": "7620218345",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1r6Htf0v2LGqdTFZ2w-_kD77Rx_WgJuz2"
 },
 {
  "Sr No": 25,
  "Team": "Nagpur Titans",
  "PlayerName": "Priyanshu Vyas",
  "Address": "Village Karoli, Post Chikarda, Teh Bhadesar, Dist Chittorgarh (Rajasthan)",
  "DOB": "05-03-2007",
  "Contact": "9116499711",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=19VBWAWrCXAHNyUl09USCrMl7C9EKZM0f"
 },
 {
  "Sr No": 26,
  "Team": "Nagpur Titans",
  "PlayerName": "Deepesh Ramchandra Ozha",
  "Address": "Surendragad",
  "DOB": "16-09-2000",
  "Contact": "9975128149",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=10mz4Q1RpkpkgPDTEvwlcSatDg5ftldcF"
 },
 {
  "Sr No": 27,
  "Team": "SSS",
  "PlayerName": "Ashwary Shrimali",
  "Address": "Sukhadia Nagar, Nathdwara",
  "DOB": "18-11-1994",
  "Contact": "7615833544",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1Jwe6cn6plpEvF7DyPlQwHv2QIfQnnl6H"
 },
 {
  "Sr No": 28,
  "Team": "SSS",
  "PlayerName": "Rajat Bhavanishankar Ji Joshi",
  "Address": "Plot no 89, Kolbaswami Society, Hazaripahad",
  "DOB": "15-03-1990",
  "Contact": "9595393929",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1n3j-tvJeQ8GEt9To_v85v2gBX-b2yI5u"
 },
 {
  "Sr No": 29,
  "Team": "SSS",
  "PlayerName": "Anil Bhawrlal Vyas",
  "Address": "Surendragarh, near Renuka Jewellers, Bajrang Chowk, Seminary Hills",
  "DOB": "05-09-1984",
  "Contact": "8390131791",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": true,
"Image": "https://drive.google.com/open?id=1h03Awxn1j6gNgRc2RwyQxgwwoqJ8t5XL"
 },
 {
  "Sr No": 30,
  "Team": "SSS",
  "PlayerName": "Umesh Rajesh Dave",
  "Address": "Surendra gadh, Seminary Hills, Nagpur",
  "DOB": "07-10-1990",
  "Contact": "8624007646",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
  "Reserved": true,
  "Image":""
 },
 {
  "Sr No": 31,
  "Team": "Not Reserved",
  "PlayerName": "Mitesh Trivedi",
  "Address": "Badkas chowk, Mahal",
  "DOB": "04-03-1988",
  "Contact": "9356202977",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1-hYYLCtqOLiGHBXSg1b8ekhNEjUq6zry"
 },
 {
  "Sr No": 32,
  "Team": "Not Reserved",
  "PlayerName": "Satish Omprakash Dave",
  "Address": "137 Abhyankar Nagar, Zenda Chowk, Nagpur",
  "DOB": "10-02-1986",
  "Contact": "9960432333",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1vnOMulP6MKLCr5AwDBFbPK4gc--zDG-N"
 },
 {
  "Sr No": 33,
  "Team": "Not Reserved",
  "PlayerName": "Dipesh Joshi",
  "Address": "Surendragadh Seminary Hills, Nagpur",
  "DOB": "01-07-1994",
  "Contact": "8446519783",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1dnA7teWt6_9PD-HJqiV6BYbwD6gC3p9u"
 },
 {
  "Sr No": 34,
  "Team": "Not Reserved",
  "PlayerName": "Rishi Dave",
  "Address": "Raipur, Chhattisgarh",
  "DOB": "12-09-2010",
  "Contact": "8269662696",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1eln8foZUeZRPZg74NMOcqmmYJvJkL0vf"
 },
 {
  "Sr No": 35,
  "Team": "Not Reserved",
  "PlayerName": "Rakesh Joshi",
  "Address": "Surendragard Veterinary College, Near Radha Krishna Mandir, Behind Vinayak Stores, Nagpur",
  "DOB": "03-10-1989",
  "Contact": "9021419629",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": ""
 },
 {
  "Sr No": 36,
  "Team": "Not Reserved",
  "PlayerName": "Yashkumar Arjunji Dave",
  "Address": "Chotta Tajbag, Nagpur",
  "DOB": "16-10-1988",
  "Contact": "9595291329",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": ""
 },
 {
  "Sr No": 37,
  "Team": "Not Reserved",
  "PlayerName": "Jitesh Trivedi",
  "Address": "Badkas chowk, RSS Building, Mahal, Nagpur",
  "DOB": "24-07-2025",
  "Contact": "9172172598",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1S12Ujh95HB1qKOZHJFK4mTlquk-DBCVh"
 },
 {
  "Sr No": 38,
  "Team": "Not Reserved",
  "PlayerName": "Bhavesh Rajesh Trivedi",
  "Address": "Seminary Hills B/H Veterinary College, Nagpur",
  "DOB": "14-09-2002",
  "Contact": "8983826746",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1Lf4UuQZhC4I3xev0S7DSjVfsnr714725"
 },
 {
  "Sr No": 39,
  "Team": "Not Reserved",
  "PlayerName": "Mayur Trivedi",
  "Address": "Chitaroli Mahal, Nagpur",
  "DOB": "05-05-1998",
  "Contact": "7620465605",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": ""
 },
 {
  "Sr No": 40,
  "Team": "Not Reserved",
  "PlayerName": "Vijay Shrimali",
  "Address": "Near RSS Building, Badkas Chowk",
  "DOB": "25-02-1988",
  "Contact": "7020438080",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=18mpT8qEXhYFKkM1IUeKfB7V9IBjaVaTr"
 },
 {
  "Sr No": 41,
  "Team": "Not Reserved",
  "PlayerName": "Kulbhushan Nirmalji Trivedi",
  "Address": "Badkas Sq, Nagpur",
  "DOB": "14-02-1992",
  "Contact": "7020427658",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": ""
 },
 {
  "Sr No": 42,
  "Team": "Not Reserved",
  "PlayerName": "Harshvardhan Ramesh Vyas",
  "Address": "Raipur",
  "DOB": "03-08-1986",
  "Contact": "8602639300",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1zWXLNb5LKLuUvcLGOi8S5iRV6JYG-pax"
 },
 {
  "Sr No": 43,
  "Team": "Not Reserved",
  "PlayerName": "Shekhar Dave",
  "Address": "Chotta Tajbag, Nagpur",
  "DOB": "22-02-1987",
  "Contact": "8955221787",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": ""
 },
 {
  "Sr No": 44,
  "Team": "Not Reserved",
  "PlayerName": "Pawan Nilkanth Joshi",
  "Address": "707 Amaltas near Shahu, Atta Chakki, Jaitala Road, Nagpur",
  "DOB": "21-10-1987",
  "Contact": "7875127431",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1PykA-c1thz8L4Lx1nVzNvg_P2tZ-hdqu"
 },
 {
  "Sr No": 45,
  "Team": "Not Reserved",
  "PlayerName": "Saurabh Mahendra Dave",
  "Address": "Raghuji Nagar, Chotta Taj Bag, Bhosale Wada, Nagpur",
  "DOB": "28-10-2001",
  "Contact": "9834275607",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1XONUD_KoCv8ZpwlV1NIVFh_Us3_Jv7mW"
 },
 {
  "Sr No": 46,
  "Team": "Not Reserved",
  "PlayerName": "Prince Deepak Trivedi",
  "Address": "Seminary Hills, Manav Seva Nagar",
  "DOB": "10-12-2009",
  "Contact": "7219225745",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1dXlm_e8gwv1uCiaUUSo6exmFU5C2FbB5"
 },
 {
  "Sr No": 47,
  "Team": "Not Reserved",
  "PlayerName": "Himanshu Yugalkishore Vidawat",
  "Address": "G.G. Complex, Friends Colony, Nagpur",
  "DOB": "30-01-2010",
  "Contact": "9423118826",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1_TpRFpzjEVM9wdUrgv7cFwS02kembS4f"
 },
 {
  "Sr No": 48,
  "Team": "Not Reserved",
  "PlayerName": "Pankaj Bhavarlal Trivedi",
  "Address": "Veterinary College, Manav Seva Nagar",
  "DOB": "17-10-1982",
  "Contact": "9890846624",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1SMOJjU8uehGYxUQqTv0ck4WQrABeV7Fu"
 },
 {
  "Sr No": 49,
  "Team": "Not Reserved",
  "PlayerName": "Hardik Devendra Ozha",
  "Address": "Seminary Hills, Nagpur",
  "DOB": "12-09-2012",
  "Contact": "9579518442",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1raJQH5kWl8FSSCD6_ytz9a7BrqgY-AeM"
 },
 {
  "Sr No": 50,
  "Team": "Not Reserved",
  "PlayerName": "Dinesh Himmatlal Joshi",
  "Address": "Seminary Hills, Manav Seva Nagar, behind Elizabeth School",
  "DOB": "25-12-1990",
  "Contact": "7620180459",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1aW1SO0Ae7LqiJkt7XRBcvZoA-JKL8Wwm"
 },
 {
  "Sr No": 51,
  "Team": "Not Reserved",
  "PlayerName": "Krishna Manoj Dave",
  "Address": "Chitaroli, Badkas Chowk, Mahal",
  "DOB": "06-09-2007",
  "Contact": "8668376056",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1DSna0HhjWPr7NQKNr3vPwTodMnJ_5aIx"
 },
 {
  "Sr No": 52,
  "Team": "Not Reserved",
  "PlayerName": "Shekhar",
  "Address": "Plot no 156, Chotta Tagbag, Bhosle Wada, Nagpur",
  "DOB": "02-02-1986",
  "Contact": "8055221786",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=14iTmg3i7poNRVwNNRtD5QIh2bIZmCraF"
 },
 {
  "Sr No": 53,
  "Team": "Not Reserved",
  "PlayerName": "Riddham Hemant Vyas",
  "Address": "Civil lines",
  "DOB": "30-12-2010",
  "Contact": "07620928284",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1Z6CQHhTdp-mSuGLmaaklBxS_oFhQGoZQ"
 },
 {
  "Sr No": 54,
  "Team": "Not Reserved",
  "PlayerName": "Jeet Bhupesh Dave",
  "Address": "Badkas chowk, Chita roli, behind Ghatate Building, Kasturi Krupa",
  "DOB": "29-12-2008",
  "Contact": "8983268696",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=14VVRqmx3CcYJEVHtR5U86UegFUdP41tf"
 },
 {
  "Sr No": 55,
  "Team": "Not Reserved",
  "PlayerName": "Ravi Gopalkrishna Dave",
  "Address": "Bungalow no 65, Shanti Villa, Dindoli Circle, Surat",
  "DOB": "08-06-1987",
  "Contact": "9924756661",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1dDepbu_eJg-UHvppk8eGbMWluXDiL2mS"
 },
 {
  "Sr No": 56,
  "Team": "Not Reserved",
  "PlayerName": "Jay Dilip Dave",
  "Address": "Atrey Layout, Pratap Nagar, Nagpur",
  "DOB": "29-05-1993",
  "Contact": "8888842220",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1UvFB8xZR3orWxx-3nwYdVYX16o7DovXh"
 },
 {
  "Sr No": 57,
  "Team": "Not Reserved",
  "PlayerName": "Yaksh Anil Vyas",
  "Address": "Surendragh Renuka Jewellers, Bajrang Chowk, Seminary Hills",
  "DOB": "13-08-2012",
  "Contact": "7507983348",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1-1mhEAgSiGh2PaxQWEh51lg4DWBUKaoI"
 },
 {
  "Sr No": 58,
  "Team": "Not Reserved",
  "PlayerName": "Yuvraj Trivedi",
  "Address": "410 C.A Road, opp Gandhibag Garden, Barwasan Corporation",
  "DOB": "08-09-2010",
  "Contact": "9511633035",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1grW2fR3yDKCqVdJytyIxGgCr_7Hh4R95"
 },
 {
  "Sr No": 59,
  "Team": "Not Reserved",
  "PlayerName": "Nishant Shrimali",
  "Address": "Mahal, Nagpur",
  "DOB": "05-04-1996",
  "Contact": "7410093103",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1QwET4Z4IxHj1xQxUE_LVxNzxg2oKpARR"
 },
 {
  "Sr No": 60,
  "Team": "Not Reserved",
  "PlayerName": "Meet Harish Trivedi",
  "Address": "Badkas Square",
  "DOB": "25-11-2005",
  "Contact": "9325005280",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=177A3N7Koc5vSofLP8WSnDO2zFmALOnzc"
 },
 {
  "Sr No": 61,
  "Team": "Not Reserved",
  "PlayerName": "Bharat Manish Vyas",
  "Address": "6 B Swagat Nagar, Hudkeshwar Road, Nagpur",
  "DOB": "10-10-1991",
  "Contact": "9579249091",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1Mz67aGFO8JpCtI8XYiGwFd6MWEMcFUv_"
 },
 {
  "Sr No": 62,
  "Team": "Not Reserved",
  "PlayerName": "Punit Umendra Shrimali",
  "Address": "Kothi Road, Mahal, Nagpur",
  "DOB": "22-11-2000",
  "Contact": "9146115807",
  "Speciality": "Bowling",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1PGhto_SxdrRhEoSa0SZWAVlhxlI_7Bbm"
 },
 {
  "Sr No": 63,
  "Team": "SSS",
  "PlayerName": "Kapil Shrimali",
  "Address": "Surendra gadh, Seminary Hills, Nagpur",
  "DOB": "24-12-2000",
  "Contact": "7023470271",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1UJDi76pBK-m4Cpzy6pXzSYjLOxKT6812"
 },
 {
  "Sr No": 64,
  "Team": "Not Reserved",
  "PlayerName": "Yash Shrimali",
  "Address": "Nagpur",
  "DOB": "04-08-1996",
  "Contact": "9672313783",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1Oy_-_jlKBeepYN_b5HUmgVBsIk14aoZj"
 },
 {
  "Sr No": 65,
  "Team": "Not Reserved",
  "PlayerName": "Yugal Shantilal Vyas",
  "Address": "Manav Seva Nagar, Nagpur",
  "DOB": "13-06-1984",
  "Contact": "9665630671",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=17GGujeeqj956jqKZNLuQEu2kCjXiJ5-B"
 },
 {
  "Sr No": 66,
  "Team": "Not Reserved",
  "PlayerName": "Joyal Dilip Joshi",
  "Address": "Society, near Elizabeth School, Seminary Hills",
  "DOB": "02-05-1989",
  "Contact": "7387575151",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1gDFj-ncSja0wpNjbXRsnqSQw-8LAuU1e"
 },
 {
  "Sr No": 67,
  "Team": "Not Reserved",
  "PlayerName": "Jay Gopalji Trivedi",
  "Address": "Badkas Sq, Mahal, Nagpur",
  "DOB": "10-03-1995",
  "Contact": "9767396288",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1hJbyunHkwMvOiocKM8rkZ-heK6S_-XSV"
 },
 {
  "Sr No": 68,
  "Team": "Not Reserved",
  "PlayerName": "Yugalkishore Kesarilal Vidawat",
  "Address": "Kesari Pushp Niwas, Seminary Hills, Nagpur",
  "DOB": "01-06-1978",
  "Contact": "9423118816",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1GMk-OXJYT_OFL7B55ycsL2ZDsnn32Zhd"
 },
 {
  "Sr No": 69,
  "Team": "Not Reserved",
  "PlayerName": "Nitin Trivedi",
  "Address": "Mumbai",
  "DOB": "26-07-1996",
  "Contact": "9461956184",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1obDmA4PyQDkqWlR1mnpwTjEwt__S_9kx"
 },
 {
  "Sr No": 70,
  "Team": "Not Reserved",
  "PlayerName": "Anup Ojha",
  "Address": "Surendra gadh, Nagpur",
  "DOB": "29-03-2001",
  "Contact": "9309109229",
  "Speciality": "Batting",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1Lif9Unq6i27x-B1KRAf656uNaYEq7u9k"
 },
 {
  "Sr No": 71,
  "Team": "Not Reserved",
  "PlayerName": "Mohit Vyas",
  "Address": "Chikarda, Teh Bhadesar, Dist Chittorgarh",
  "DOB": "15-09-2001",
  "Contact": "9509273772",
  "Speciality": "All-Rounder",
  "Price": 0,
 "Sold": "No",
"Reserved": false,
"Image": "https://drive.google.com/open?id=1Icx_Bf53qY3Nczh7MCDKugULabhEU_de"
 }

]